package(default_applicable_licenses = ["@rules_java//:license"])

alias(
    name = "common",
    actual = "//java/runtime/warmup/src/main/java/com/google/devtools/build/rules_java/warmup/common",
    visibility = ["//visibility:public"],
)

alias(
    name = "wire",
    actual = "//java/runtime/warmup/src/main/java/com/google/devtools/build/rules_java/warmup/common/wire",
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//java/runtime/warmup/src/main/java/com/google/devtools/build/rules_java/warmup/common:srcs",
    ],
    visibility = ["//java:__pkg__"],
)
