# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("//java:defs.bzl", "java_binary", "java_library")
load("//java/bazel/rules:jvm_test_info.bzl", "jvm_persistent_test_runner_info")

package(default_applicable_licenses = ["@rules_java//:license"])

java_binary(
    name = "persistent_test_runner",
    srcs = [
        "Config.java",
        "CoordinatorStore.java",
        "JvmPool.java",
        "JvmProcess.java",
        "PersistentTestRunner.java",
        "WrapperArgs.java",
    ],
    main_class = "com.google.devtools.build.java.testrunner.PersistentTestRunner",
    visibility = ["//visibility:public"],
    deps = [
        "//java/bazel/rules/test_runner/persistent_worker:persistent_worker_lib",
        "//java/bazel/rules/test_runner/wire",
        "//java/runfiles",
    ],
)

java_library(
    name = "jvm_driver",
    srcs = ["JvmDriver.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//java/bazel/rules/test_runner/extension",
        "//java/bazel/rules/test_runner/wire",
    ],
)

java_binary(
    name = "scan_jvm_test_runner_extensions",
    srcs = ["ScanJvmTestRunnerExtensions.java"],
    main_class = "com.google.devtools.build.java.testrunner.ScanJvmTestRunnerExtensions",
    visibility = ["//visibility:public"],
    deps = ["//java/bazel/rules/test_runner/persistent_worker:persistent_worker_lib"],
)

java_binary(
    name = "extension_aggregator",
    srcs = ["ExtensionAggregator.java"],
    main_class = "com.google.devtools.build.java.testrunner.ExtensionAggregator",
    visibility = ["//visibility:public"],
)

jvm_persistent_test_runner_info(
    name = "jvm_persistent_test_runner_info",
    additional_deps = [":jvm_driver"],
    runner = ":persistent_test_runner",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "persistent_test_runner_toolchain",
    toolchain = ":jvm_persistent_test_runner_info",
    toolchain_type = "//java/bazel/rules:jvm_test_toolchain_type",
    visibility = ["//visibility:public"],
)
